- src/country-national-animal.json
Source http://en.wikipedia.org/wiki/List_of_national_animals
> Changed Danish national animal to Mute Swan.

- src/country-capital-city.json
The capital city of Australia is Canberra.
http://en.wikipedia.org/wiki/Canberra
> Corrected Australian capital city.

- README.md
included a node.js example and also reformatted the PHP example to match the .editorconfig file. Spotted the file path in the PHP example '/src/country-city.json', does not exist so changed it to '/src/country-capital-city.json'
> node.js example

- README.md
My Ruby skills are humble, but parsing a JSON file is far from complicated.
> Added a simple Ruby example | #19

- README.md
Not an amazing Python coder too, but it does work on Python 2.7. Refs #18
> Added a simple Python example

- src/country-currency-name-and-code.json
Fixing the name and code for Moldova
> Fixing the name and code for Moldova

- README.md
> Add links to each files in readme

- src/country-by-capital-city.json
https://en.wikipedia.org/wiki/Brazil
the capitals with accents are truncated on that file
> correct capital of Brazil

- src/country-by-capital-city.json
> Changes Teheran to Tehran

- src/country-by-national-dish.json
- src/country-by-national-symbol.json
thanks for the repo. quite useful. wanted to add Nepal's national symbol
> add nepal's national symbol

- src/country-by-abbreviation.json
See issue https://github.com/samayo/country-json/issues/104
per https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
> Fix invalid abbreviations

- src/country-by-population.json
Some of the population data was very out of date, so I've updated it from this article: https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations). Population numbers come from 1st July 2017.
> Updated population data from Wikipedia.

- src/country-by-calling-code.json
Hello!
This PR replaces `null` values for country codes, with ones that I had looked up.
Thanks for the nice work on the repo :-)
> Add Missing Country Codes

- src/country-by-capital-city.json
- src/country-by-currency-name.json
- src/country-by-government-type.json
- src/country-by-life-expectancy.json
- src/country-by-national-dish.json
- src/country-by-region-in-world.json
- src/country-by-yearly-average-temperature.json
United Kingdom and United States had null entries...
> Add more USD and GBP countries

- src/country-by-currency-code.json
- src/country-by-currency-name.json
Add currency names of 30 of 31 countries in country_by_currency_name.json file. Also, Macau and Pitcairn Islands' name are fixed according to official. Each additions' references are down below. Only not sure of Palestine, which are a bit confusing since there are no official currency in the country.
Bosnia and Herzegovina: [Wikipedia](https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina)
England: [Wikipedia](https://en.wikipedia.org/wiki/England)
Brunei: [Wikipedia](https://en.wikipedia.org/wiki/Brunei)
Chad: [Wikipedia](https://en.wikipedia.org/wiki/Chad)
Czech Republic: [Wikipedia](https://en.wikipedia.org/wiki/Czech_Republic)
East Timor: [Wikipedia](https://en.wikipedia.org/wiki/East_Timor)
Falkland Islands: [Wikipedia](https://en.wikipedia.org/wiki/Falkland_Islands)
Fiji Islands: …
> Add missing currency names

- src/country-by-capital-city.json
fixed capital of chad from ndjam to ndjamena
> fixed samayo/country-json#246

- .github/workflows/validate.yml
I did these as individual commits so you can cherry pick if you don't want some of them. For example, the entry for Saint Pierre and Miquelon is the unofficial flag.
> Add some missing flags, fix flag of spain, add workflow to check JSON

- src/country-by-currency-code.json
These countries now use euros.
https://european-union.europa.eu/institutions-law-budget/euro/countries-using-euro_en
> update newer countries to use euro

- src/country-by-capital-city.json
Changed the capital of colombia to bogota
This solves #241
> #241 Fix capital of colombia

- src/country-by-yearly-average-temperature.json
Fixes #262, and [also matches source with Wikipedia](https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature). Data downloaded from the [Climate Change Knowledge Portal](https://climateknowledgeportal.worldbank.org/download-data)
> Update average yearly temperatures to World Bank dataset

- src/country-by-abbreviation.json
- src/country-by-alphabet-letters.json
- src/country-by-avg-male-height.json
- src/country-by-barcode-prefix.json
- src/country-by-calling-code.json
- src/country-by-capital-city.json
- src/country-by-cities.json
- src/country-by-continent.json
- src/country-by-costline.json
- src/country-by-currency-code.json
- src/country-by-currency-name.json
- src/country-by-domain-tld.json
- src/country-by-elevation.json
- src/country-by-geo-coordinates.json
- src/country-by-government-type.json
- src/country-by-independence-date.json
- src/country-by-iso-numeric.json
- src/country-by-landlocked.json
- src/country-by-languages.json
- src/country-by-life-expectancy.json
- src/country-by-name.json
- src/country-by-national-dish.json
- src/country-by-national-symbol.json
- src/country-by-population-density.json
- src/country-by-population.json
- src/country-by-region-in-world.json
- src/country-by-religion.json
- src/country-by-surface-area.json
- src/country-by-yearly-average-temperature.json
Fixes #263 
Note: Abbreviations, TLD, and currency name/code has remained the same
> Update names of Libya and Eswatini

- src/country-by-religion.json
> Update The Democratic Republic of Congo name in religion dataset

- src/country-by-religion.json
> Fix typo in country-by-religion.json
